# Generated by Django 4.0.4 on 2022-06-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True)),
                ('direcciones', models.CharField(max_length=50)),
                ('saldo', models.FloatField(null=True)),
                ('límite_credito', models.FloatField()),
                ('premium', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('numero', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad', models.IntegerField(default=1)),
                ('articulos', models.ManyToManyField(to='main.articulo')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='fabricas',
            field=models.ManyToManyField(to='main.fabrica'),
        ),
    ]
