# Generated by Django 4.0.4 on 2022-06-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.orden'),
        ),
    ]
