# Generated by Django 4.0.4 on 2022-06-14 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_avisos_banco_cuentascorrientes_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avisos',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='descripcion_ampliada',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2022, 6, 14, 14, 51, 10, 416935)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='clasificacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='numero_asiento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2022, 6, 14, 14, 51, 10, 414935)),
        ),
    ]
