# Generated by Django 4.0.4 on 2022-06-15 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usuario_empresa_alter_avisos_asunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 44, 25, 647474)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2022, 6, 15, 13, 44, 25, 646474)),
        ),
    ]
