# Generated by Django 4.0.4 on 2022-06-15 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movimientosbancarios_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 51, 42, 8964)),
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsables'),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 51, 42, 9963)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsables'),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 51, 42, 7963)),
        ),
    ]
