# Generated by Django 4.0.4 on 2022-06-15 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_movimientosbancarios_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cuentascorrientes'),
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 54, 41, 290025)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cuentascorrientes'),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 54, 41, 291024)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 15, 13, 54, 41, 290025)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.banco'),
        ),
    ]
