# Generated by Django 4.0.4 on 2022-06-21 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_movimientosbancarios_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='documento',
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 36, 56, 195345)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 36, 56, 196347)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 36, 56, 194346)),
        ),
    ]
