# Generated by Django 4.0.4 on 2022-06-21 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_banco_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 37, 58, 886630)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 37, 58, 887624)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 0, 37, 58, 885625)),
        ),
    ]
