# Generated by Django 4.0.4 on 2022-06-21 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_movimientosbancarios_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 1, 29, 55, 641046)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 1, 29, 55, 642047)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 1, 29, 55, 640048)),
        ),
    ]
