# Generated by Django 4.0.4 on 2022-06-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_movimientosbancarios_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoserp',
            name='es_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 51, 41, 862509)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 51, 41, 863509)),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 51, 41, 861523)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(max_length=50),
        ),
    ]
