# Generated by Django 4.0.4 on 2022-06-30 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_movimientoserp_es_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 52, 31, 453289)),
        ),
        migrations.AlterField(
            model_name='movimientoserp',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 52, 31, 455290)),
        ),
        migrations.AlterField(
            model_name='saldosbancarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 14, 52, 31, 452290)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(),
        ),
    ]
